[package]
name = "teo-mongodb-connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { version = "2.7.0", optional = true }
bson = { version = "2.7.0", features = ["chrono-0_4", "serde_with"], optional = true }
async-recursion = "1.0.5"
async-trait = "0.1.74"
